### ISSUE TITLE
panic: send on closed channel

### ISSUE THREAD

**Issue by pracucci** [minio/minio-go#1695]
Grafana Mimir is currently vendoring Minio client v7.0.30 and an user reported the following panic:

```
panic: send on closed channel

goroutine 1604297 [running]:
github.com/minio/minio-go/v7.(*Object).doGetRequest(_, {{0xc007f76000, 0x3e80, 0x3e80}, 0x0, 0x0, 0x1, 0x0, 0x1, 0x0, ...})
    /__w/mimir/mimir/vendor/github.com/minio/minio-go/v7/api-get-object.go:319 +0xdc
github.com/minio/minio-go/v7.(*Object).Read(0xc000a42700, {0xc007f76000?, 0x77?, 0xc00676bb78?})
    /__w/mimir/mimir/vendor/github.com/minio/minio-go/v7/api-get-object.go:399 +0x248
github.com/thanos-io/thanos/pkg/objstore.(*timingReadCloser).Read(0xc009a8fea0, {0xc007f76000?, 0x77?, 0xc00676bbf0?})
    /__w/mimir/mimir/vendor/github.com/thanos-io/thanos/pkg/objstore/objstore.go:651 +0x32
github.com/thanos-io/thanos/pkg/objstore.(*tracingReadCloser).Read(0xc0051e3500, {0xc007f76000?, 0x0?, 0x7f474082d108?})
    /__w/mimir/mimir/vendor/github.com/thanos-io/thanos/pkg/objstore/tracing.go:138 +0x32
bufio.(*Reader).Read(0xc0059ea5a0, {0xc007f7a000, 0x54, 0x44ff72?})
    /usr/local/go/src/bufio/bufio.go:236 +0x1b4
io.ReadAtLeast({0x2564000, 0xc0059ea5a0}, {0xc007f7a000, 0x54, 0x3e80}, 0x54)
    /usr/local/go/src/io/io.go:331 +0x9a
io.ReadFull(...)
    /usr/local/go/src/io/io.go:350
github.com/grafana/mimir/pkg/storegateway.(*bucketChunkReader).loadChunks(0xc005f73920, {0x257f680, 0xc009af4200}, {0xc008114000, 0x109, 0xc000cb3870?}, {0x0, 0x0, 0x0}, 0x12, ...)
    /__w/mimir/mimir/pkg/storegateway/bucket.go:2656 +0x5dd
github.com/grafana/mimir/pkg/storegateway.(*bucketChunkReader).load.func3()
    /__w/mimir/mimir/pkg/storegateway/bucket.go:2592 +0xa5
golang.org/x/sync/errgroup.(*Group).Go.func1()
    /__w/mimir/mimir/vendor/golang.org/x/sync/errgroup/errgroup.go:75 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
    /__w/mimir/mimir/vendor/golang.org/x/sync/errgroup/errgroup.go:72 +0xa5
```

The panic looks happening here:
https://github.com/grafana/mimir/blob/ae57256871ced9909a91269aeddb7c61a9408383/vendor/github.com/minio/minio-go/v7/api-get-object.go#L319-L323

Which according to Minio `master`  is:
https://github.com/minio/minio-go/blob/def1174273a854f399c8b5bd1dfb66189dc287c7/api-get-object.go#L306-L310

Looks like happening when `doGetRequest()` is called but `o.reqCh` is already closed. The version 7.0.30 already includes the fix done in https://github.com/minio/minio-go/pull/1670 so I think this may be another variation of the same issue.

What do you think?

**Comment by harshavardhana** [comment]
https://github.com/minio/minio-go/commit/b65486d0c6af0b6a92f61df200240199a29f3ed6 this is also needed.

**Comment by pracucci** [comment]
Thanks for the quick reply. Will do upgrade to latest, thanks!
