### ISSUE TITLE
Not able to do s3 csv extract with Azure File Share PV/PVC mount

### ISSUE THREAD

**Issue by binnie268** [minio/minio-go#1717]
When we use docker desktop  kubernetes with direct pv/pvc volume mount for minio, we are able to getObject with x-minio-extract: true. When we deploy the same change to our DEV  Azure kubernetes environment which is using Azure File Share, it's mounted with PV/PVC to minio, we are seeing errors.

**Versions Used:**
Minio-go 7.0.34 (7.0.42 also doesn't work)
bitnami/minio:2022.8.13-debian-11-r0
Azure FileShare:
  storageClassName: azurefile-csi-minio
  volumeMode: Filesystem

**This is the stack trace:**
```
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InternalError</Code><Message>We encountered an internal error, please try again.</Message><Resource>/data-uploads/[PORTABILITY_TESTING]Methodology_config_AFC.zip/332/swift_load_bs_[1].csv</Resource><RequestId>17215B3DE64C67DA</RequestId><HostId>788e3319-ac36-42c3-bdf1-c63970ca80af</HostId></Error>---------END-HTTP---------
---------START-HTTP---------
GET /data-uploads/%5BPORTABILITY_TESTING_SCHEMA_INCLUDED%5D%5BSWIFT%5D_Methodology_config_AFC.zip/332/swift_load_bs_%5B1%5D.csv HTTP/1.1
Host: minio:9000
User-Agent: MinIO (linux; amd64) minio-go/v7.0.24
Authorization: AWS4-HMAC-SHA256 Credential=minioadmin/20221025/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date;x-minio-extract, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20221025T160058Z
X-Minio-Extract: true
Accept-Encoding: gzip

HTTP/1.1 500 Internal Server Error
Content-Length: 374
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Tue, 25 Oct 2022 16:00:58 GMT
No-Gzip-Compression: true
Server: MinIO
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
Vary: Accept-Encoding
X-Amz-Request-Id: 17215B3DF2161F93
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InternalError</Code><Message>We encountered an internal error, please try again.</Message><Resource>/data-uploads/[PORTABILITY_TESTING]Methodology_config_AFC.zip/332/swift_load_bs_[1].csv</Resource><RequestId>17215B3DF2161F93</RequestId><HostId>788e3319-ac36-42c3-bdf1-c63970ca80af</HostId></Error>---------END-HTTP---------
ERROR[2022-10-25T16:00:59Z] error reading from minio reader ReadLine()    error="We encountered an internal error, please try again." method=validateFile
ERROR[2022-10-25T16:00:59Z] error on data source validation               error="We encountered an internal error, please try again." method=Validate
```

**This is the minio logs:**
```
API: GetObject(bucket=data-uploads, object=[PORTABILITY_TESTING_SCHEMA_INCLUDED][SWIFT]_Methodology_config_AFC.zip/332/swift_load_bs_[1].csv)
Time: 12:52:10 UTC 10/25/2022
DeploymentID: 788e3319-ac36-42c3-bdf1-c63970ca80af
RequestID: 172150F072700039
RemoteHost: 172.20.0.10
Host: minio:9000
UserAgent: MinIO (linux; amd64) minio-go/v7.0.34
Error: not implemented (*errors.errorString)
       7: internal/logger/logger.go:259:logger.LogIf()
       6: internal/logger/logger.go:385:logger.CriticalIf()
       5: cmd/gateway-unsupported.go:58:cmd.GatewayUnsupported.PutObjectMetadata()
       4: cmd/s3-zip-handlers.go:507:cmd.updateObjectMetadataWithZipInfo()
       3: cmd/s3-zip-handlers.go:145:cmd.objectAPIHandlers.getObjectInArchiveFileHandler()
       2: cmd/object-handlers.go:603:cmd.objectAPIHandlers.GetObjectHandler()
       1: net/http/server.go:2084:http.HandlerFunc.ServeHTTP()
critical: "GET /data-uploads/%5BPORTABILITY_TESTING%5D%_Methodology_config_AFC.zip/332/swift_load_bs_%5B1%5D.csv": {}
goroutine 60089 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x65
github.com/minio/minio/cmd.setCriticalErrorHandler.func1.1()
	github.com/minio/minio/cmd/generic-handlers.go:573 +0x2e5
panic({0x23b9020, 0x60f7740})
	runtime/panic.go:838 +0x207
github.com/minio/minio/internal/logger.CriticalIf(...)
	github.com/minio/minio/internal/logger/logger.go:386
github.com/minio/minio/cmd.GatewayUnsupported.PutObjectMetadata({}, {_, _}, {_, _}, {_, _}, {{0x0, 0x0}, 0x0, ...})
	github.com/minio/minio/cmd/gateway-unsupported.go:58 +0xb2
github.com/minio/minio/cmd.updateObjectMetadataWithZipInfo({_, _}, {_, _}, {_, _}, {_, _}, {{0x0, 0x0}, ...})
	github.com/minio/minio/cmd/s3-zip-handlers.go:507 +0x50e
github.com/minio/minio/cmd.objectAPIHandlers.getObjectInArchiveFileHandler({0x498cae8?, 0x498cad8?}, {0x4d9cde0?, 0xc00221ab40}, {0x4db9550, 0xc00312c000}, {0xc001f10201, 0xc}, {0xc01496a8c0, 0x61}, ...)
	github.com/minio/minio/cmd/s3-zip-handlers.go:145 +0xa58
github.com/minio/minio/cmd.objectAPIHandlers.GetObjectHandler({0x498cae8?, 0x498cad8?}, {0x4d99080, 0xc0030d8a00}, 0xc001068f00)
	github.com/minio/minio/cmd/object-handlers.go:603 +0x3b3
net/http.HandlerFunc.ServeHTTP(...)
	net/http/server.go:2084
github.com/minio/minio/cmd.httpTrace.func1({0x4d99080, 0xc0030d8a00}, 0xc001068f00)
	github.com/minio/minio/cmd/http-tracer.go:238 +0x1af
net/http.HandlerFunc.ServeHTTP(0x2313780?, {0x4d99080?, 0xc0030d8a00?}, 0x4?)
	net/http/server.go:2084 +0x2f
github.com/klauspost/compress/gzhttp.NewWrapper.func1.1({0x4d99080, 0xc0030d8a00}, 0x76749c?)
	github.com/klauspost/compress@v1.15.9/gzhttp/compress.go:391 +0x347
net/http.HandlerFunc.ServeHTTP(...)
	net/http/server.go:2084
github.com/minio/minio/cmd.maxClients.func1({0x4d99080, 0xc0030d8a00}, 0xc001068f00)
	github.com/minio/minio/cmd/handler-api.go:277 +0x4cc
net/http.HandlerFunc.ServeHTTP(...)
	net/http/server.go:2084
github.com/minio/minio/cmd.collectAPIStats.func1({0x4d99080, 0xc0030d88c0}, 0x10?)
	github.com/minio/minio/cmd/handler-utils.go:356 +0x106
net/http.HandlerFunc.ServeHTTP(0xc0013fcb34?, {0x4d99080?, 0xc0030d88c0?}, 0xc0013fcb34?)
	net/http/server.go:2084 +0x2f
github.com/minio/minio/cmd.setBucketForwardingHandler.func1({0x4d99080, 0xc0030d88c0}, 0xc001068f00)
	github.com/minio/minio/cmd/generic-handlers.go:486 +0x22d
net/http.HandlerFunc.ServeHTTP(0x4d99020?, {0x4d99080?, 0xc0030d88c0?}, 0x10?)
	net/http/server.go:2084 +0x2f
github.com/minio/minio/cmd.addCustomHeaders.func1({0x4d99020, 0xc0028fd0c8}, 0xc001061760?)
	github.com/minio/minio/cmd/generic-handlers.go:561 +0x3c2
net/http.HandlerFunc.ServeHTTP(0x26b7340?, {0x4d99020?, 0xc0028fd0c8?}, 0x39?)
	net/http/server.go:2084 +0x2f
github.com/minio/minio/cmd.setRequestValidityHandler.func1({0x4d99020, 0xc0028fd0c8}, 0xc001068f00)
	github.com/minio/minio/cmd/generic-handlers.go:474 +0xe06
net/http.HandlerFunc.ServeHTTP(0x40?, {0x4d99020?, 0xc0028fd0c8?}, 0x605ac10?)
	net/http/server.go:2084 +0x2f
github.com/minio/minio/cmd.setHTTPStatsHandler.func1({0x4d9b6f0?, 0xc018574d20}, 0xc001068f00)
	github.com/minio/minio/cmd/generic-handlers.go:312 +0x119
net/http.HandlerFunc.ServeHTTP(0xc00221ab10?, {0x4d9b6f0?, 0xc018574d20?}, 0xc0?)
	net/http/server.go:2084 +0x2f
github.com/minio/minio/cmd.setRequestLimitHandler.func1({0x4d9b6f0?, 0xc018574d20}, 0xc001068f00)
	github.com/minio/minio/cmd/generic-handlers.go:125 +0x49b
net/http.HandlerFunc.ServeHTTP(0x2799a38?, {0x4d9b6f0?, 0xc018574d20?}, 0x1f38c56?)
	net/http/server.go:2084 +0x2f
github.com/minio/minio/cmd.setCrossDomainPolicy.func1({0x4d9b6f0?, 0xc018574d20?}, 0x6?)
	github.com/minio/minio/cmd/crossdomain-xml-handler.go:43 +0xef
net/http.HandlerFunc.ServeHTTP(0xc001068f00?, {0x4d9b6f0?, 0xc018574d20?}, 0x1?)
	net/http/server.go:2084 +0x2f
github.com/minio/minio/cmd.setBrowserRedirectHandler.func1({0x4d9b6f0, 0xc018574d20}, 0xc001068f00)
	github.com/minio/minio/cmd/generic-handlers.go:156 +0x183
net/http.HandlerFunc.ServeHTTP(0x0?, {0x4d9b6f0?, 0xc018574d20?}, 0x2c78395c?)
	net/http/server.go:2084 +0x2f
github.com/minio/minio/cmd.setAuthHandler.func1({0x4d9b6f0, 0xc018574d20}, 0xc001068f00)
	github.com/minio/minio/cmd/auth-handler.go:537 +0x4ea
net/http.HandlerFunc.ServeHTTP(0xc0003cbd40?, {0x4d9b6f0?, 0xc018574d20?}, 0x60f70a0?)
	net/http/server.go:2084 +0x2f
github.com/minio/minio/cmd.httpTracer.func1({0x4d9b6f0, 0xc018574d20}, 0xc001068f00)
	github.com/minio/minio/cmd/http-tracer.go:129 +0x629
net/http.HandlerFunc.ServeHTTP(0xc001068e00?, {0x4d9b6f0?, 0xc018574d20?}, 0x50000000498ef50?)
	net/http/server.go:2084 +0x2f
github.com/gorilla/mux.(*Router).ServeHTTP(0xc003082300, {0x4d9b6f0, 0xc018574d20}, 0xc001068d00)
	github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1cf
github.com/rs/cors.(*Cors).Handler.func1({0x4d9b6f0, 0xc018574d20}, 0xc001068d00)
	github.com/rs/cors@v1.7.0/cors.go:219 +0x1bd
net/http.HandlerFunc.ServeHTTP(0x4666eb?, {0x4d9b6f0?, 0xc018574d20?}, 0xc0015659c0?)
	net/http/server.go:2084 +0x2f
github.com/minio/minio/cmd.setCriticalErrorHandler.func1({0x4d9b6f0?, 0xc018574d20?}, 0x0?)
	github.com/minio/minio/cmd/generic-handlers.go:585 +0x83
net/http.HandlerFunc.ServeHTTP(0x3f780?, {0x4d9b6f0?, 0xc018574d20?}, 0x0?)
	net/http/server.go:2084 +0x2f
github.com/minio/minio/internal/http.(*Server).Start.func1({0x4d9b6f0?, 0xc018574d20?}, 0x4a63a0?)
	github.com/minio/minio/internal/http/server.go:111 +0x19c
net/http.HandlerFunc.ServeHTTP(0x0?, {0x4d9b6f0?, 0xc018574d20?}, 0xc003b06400?)
	net/http/server.go:2084 +0x2f
net/http.serverHandler.ServeHTTP({0xc002ddffb0?}, {0x4d9b6f0, 0xc018574d20}, 0xc001068d00)
	net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc0033fff40, {0x4d9cde0, 0xc0006beba0})
	net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
	net/http/server.go:3071 +0x4db
```

**Comment by klauspost** [comment]
Gateway is removed, so this cannot be fixed.

**Comment by binnie268** [comment]
Understood, could we add this note into this article: https://blog.min.io/small-file-archives/

**Comment by klauspost** [comment]
@binnie268 The gateway has been deprecated since July 2020, and is now fully removed.
