### ISSUE TITLE
Segfault when trying to upload image buffer

### ISSUE THREAD

**Issue by danhab99** [minio/minio-go#1746]
```go
	minioClient, err = minio.New(config.MinioEndpoint, &minio.Options{
		Creds:  credentials.NewStaticV4(config.MinioAccessKey, config.MinioSecretKey, ""),
		Secure: true,
	})

                        var inputImage image.Image // is defined
			buffer := new(bytes.Buffer)
			writer := bufio.NewWriter(buffer)
			err = png.Encode(writer, inputImage)
			if err != nil {
				panic(err)
			}

			putCtx := context.Background()
			_, err := ctx.minioClient.PutObject(putCtx,"unprocessed", pub.ObjName, buffer, buffer.Len(), minio.PutObjectOptions{
				ContentType: "image/png",
			})
			if err != nil {
				panic(err)
			}
``` 

Results in

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x82da16]

goroutine 69 [running]:
github.com/minio/minio-go/v7.(*Client).putObjectCommon(_, {_, _}, {_, _}, {_, _}, {_, _}, 0xffffffffffffffff, ...)
	/home/dan/go/pkg/mod/github.com/minio/minio-go/v7@v7.0.45/api-put-object.go:255 +0xf6
github.com/minio/minio-go/v7.(*Client).PutObject(_, {_, _}, {_, _}, {_, _}, {_, _}, 0xffffffffffffffff, ...)
	/home/dan/go/pkg/mod/github.com/minio/minio-go/v7@v7.0.45/api-put-object.go:245 +0x245
project/lib/interactions.InteractionsCtx.PublishProcessTask.func1()
	/home/dan/go/src/project/lib/interactions/processed_image.go:85 +0x58e
created by project/lib/interactions.InteractionsCtx.PublishProcessTask
	/home/dan/go/src/project/lib/interactions/processed_image.go:60 +0x150
exit status 2
make: *** [makefile:2: test] Error 1
```

**Comment by harshavardhana** [comment]
@danhab99 looks like your minioClient is not initialized properly

**Comment by danhab99** [comment]
@harshavardhana Editted my comment with the init code

**Comment by harshavardhana** [comment]
You are not handling any error returned via minio.New() @danhab99

**Comment by danhab99** [comment]
OH MY GOD you're right..... im sorry

**Comment by harshavardhana** [comment]
> OH MY GOD you're right..... im sorry

Glad it worked 👍🏼
