### ISSUE TITLE
Panic in signv2

### ISSUE THREAD

**Issue by klingtnet** [minio/minio-go#375]
The call to `sort.Strings(resourceList)` in function `writeCanonicalizedResource` from [`api-signature-v2.go`](https://github.com/minio/minio-go/blob/master/request-signature-v2.go#L274) can panic. Here is the stacktrace:

```
panic: runtime error: index out of range

goroutine 892 [running]:
panic(0x8c4e80, 0xc820010080)
/usr/lib/go/src/runtime/panic.go:464 +0x3e6
sort.(*StringSlice).Less(0xc8221f3b40, 0x0, 0xffffffffffffffff, 0x1)
<autogenerated>:13 +0x114
sort.doPivot(0x7f4c2eaee8a0, 0xc8221f3b40, 0x0, 0x14, 0xc8221f3b40, 0x18)
/usr/lib/go/src/sort/sort.go:128 +0x27b
sort.quickSort(0x7f4c2eaee8a0, 0xc8221f3b40, 0x0, 0x14, 0x9)
/usr/lib/go/src/sort/sort.go:195 +0xa3
sort.Sort(0x7f4c2eaee8a0, 0xc8221f3b40)
/usr/lib/go/src/sort/sort.go:229 +0x74
sort.Strings(0xbeb9e0, 0x14, 0x14)
/usr/lib/go/src/sort/sort.go:305 +0x86
/cephy/vendor/github.com/minio/minio-go.writeCanonicalizedResource(0xc8202c2d20, 0x9587f8, 0x3, 0xc820271100, 0x964de0, 0x8, 0x1, 0x1, 0xc82041fa10, 0x0, ...)
src/cephy/vendor/github.com/minio/minio-go/request-signature-v2.go:274 +0x92
/cephy/vendor/github.com/minio/minio-go.getStringToSignV2(0x9587f8, 0x3, 0xc820271100, 0x964de0, 0x8, 0x1, 0x1, 0xc82041fa10, 0x0, 0x0, ...)
src/cephy/vendor/github.com/minio/minio-go/request-signature-v2.go:187 +0xb8
/cephy/vendor/github.com/minio/minio-go.signV2(0x9587f8, 0x3, 0xc820271100, 0x964de0, 0x8, 0x1, 0x1, 0xc82041fa10, 0x0, 0x0, ...)
src/cephy/vendor/github.com/minio/minio-go/request-signature-v2.go:155 +0x1d6
/cephy/vendor/github.com/minio/minio-go.Client.newRequest(0xc820139080, 0x14, 0xc820013d10, 0x28, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
src/cephy/vendor/github.com/minio/minio-go/api.go:430 +0x954
/cephy/vendor/github.com/minio/minio-go.Client.getObject(0xc820139080, 0x14, 0xc820013d10, 0x28, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
src/cephy/vendor/github.com/minio/minio-go/api-get.go:492 +0x45d
/cephy/vendor/github.com/minio/minio-go.Client.GetObject.func1(0xc822306060, 0xc8223060c0, 0xc822306120, 0xc8209f2510, 0xc820139080, 0x14, 0xc820013d10, 0x28, 0x2, 0x0, ...)
src/cephy/vendor/github.com/minio/minio-go/api-get.go:181 +0x243
created by /cephy/vendor/github.com/minio/minio-go.Client.GetObject
src/cephy/vendor/github.com/minio/minio-go/api-get.go:200 +0x30b
panic: send on closed channel
```

I couldn't determine what exactly caused the panic but everything works fine when i remove the `sort` call.
Is sorting the `resourceList` on every call even necessary? I couldn't find any guarantees in the [go language spec](https://golang.org/ref/spec#Array_types) about the order of elements in array declarations, but it seems that the elements have exactly the same order as they're specified in the array declaration.

**Comment by vadmeste** [comment]
@klingtnet, is your code concurrent ? are you using more than one go routine which call minio-go library at the same time ?

**Comment by klingtnet** [comment]
Yes, I'm using about a hundred go routines.

**Comment by vadmeste** [comment]
By the way @team, you could check if resourceList in https://github.com/minio/minio-go/blob/master/request-signature-v2.go#L239 is correctly sorted in unit tests instead of sorting it each time.
