### ISSUE TITLE
Tests: Running go test -race ./... causes SIGQUIT

### ISSUE THREAD

**Issue by awwalker** [minio/minio-go#464]
```
=== RUN   TestResumableFPutObject
SIGQUIT: quit
PC=0x63a5b m=0

goroutine 0 [idle]:
runtime.mach_semaphore_wait(0x23000001003, 0x208ad000165, 0x1, 0x208ad000165, 0x0, 0x911a40, 0x57019, 0xffffffffffffffff, 0x9118e8, 0x7fff5fbff4e4, ...)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/sys_darwin_amd64.s:411 +0xb
runtime.semasleep1(0xffffffffffffffff, 0x9118e8)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/os1_darwin.go:423 +0xdf
runtime.semasleep.func1()
	/usr/local/Cellar/go/1.6/libexec/src/runtime/os1_darwin.go:439 +0x29
runtime.systemstack(0x7fff5fbff4e8)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/asm_amd64.s:307 +0xab
runtime.semasleep(0xffffffffffffffff, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/os1_darwin.go:440 +0x36
runtime.notesleep(0x9120e8)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/lock_sema.go:166 +0xed
runtime.stopm()
	/usr/local/Cellar/go/1.6/libexec/src/runtime/proc.go:1535 +0x10b
runtime.findrunnable(0xc820018000, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/proc.go:1973 +0x808
runtime.schedule()
	/usr/local/Cellar/go/1.6/libexec/src/runtime/proc.go:2072 +0x2a6
runtime.park_m(0xc8203c8180)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/proc.go:2137 +0x157
runtime.mcall(0x57960)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/asm_amd64.s:233 +0x5b

goroutine 1 [chan receive]:
testing.RunTests(0x762418, 0x90f840, 0x4e, 0x4e, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/testing/testing.go:583 +0xb39
testing.(*M).Run(0xc8214a7f00, 0x24)
	/usr/local/Cellar/go/1.6/libexec/src/testing/testing.go:515 +0x11e
main.main()
	github.com/minio/minio-go/_test/_testmain.go:208 +0x211

goroutine 17 [syscall, 9 minutes, locked to thread]:
runtime.goexit()
	/usr/local/Cellar/go/1.6/libexec/src/runtime/asm_amd64.s:1998 +0x1

goroutine 279 [select, 8 minutes]:
net/http.(*persistConn).readLoop(0xc82006c340)
	/usr/local/Cellar/go/1.6/libexec/src/net/http/transport.go:1178 +0x118c
created by net/http.(*Transport).dialConn
	/usr/local/Cellar/go/1.6/libexec/src/net/http/transport.go:853 +0x16f0

goroutine 29 [select, 9 minutes]:
github.com/minio/minio-go.Client.GetObject.func1(0xc820576180, 0xc8205761e0, 0xc820576240, 0xc8201f6580, 0xc8201f6590, 0xc8204b21e0, 0xc8201bad60, 0x1e, 0xc820172150, 0x28)
	/Users/aaronwalker/go/src/github.com/minio/minio-go/api-get-object.go:59 +0x63a
created by github.com/minio/minio-go.Client.GetObject
	/Users/aaronwalker/go/src/github.com/minio/minio-go/api-get-object.go:99 +0x460

goroutine 354 [select, 8 minutes]:
github.com/minio/minio-go.Client.GetObject.func1(0xc820280d80, 0xc820280de0, 0xc820280e40, 0xc82017a110, 0xc82017a120, 0xc8203cd7c0, 0xc82019e3a0, 0x1e, 0xc8204dc000, 0x24)
	/Users/aaronwalker/go/src/github.com/minio/minio-go/api-get-object.go:59 +0x63a
created by github.com/minio/minio-go.Client.GetObject
	/Users/aaronwalker/go/src/github.com/minio/minio-go/api-get-object.go:99 +0x460

goroutine 229 [select, 8 minutes]:
github.com/minio/minio-go.Client.GetObject.func1(0xc8202802a0, 0xc820280300, 0xc820280360, 0xc8201ec4c0, 0xc8201ec4e0, 0xc820436280, 0xc820476d00, 0x1e, 0xc8204702e0, 0x1e)
	/Users/aaronwalker/go/src/github.com/minio/minio-go/api-get-object.go:59 +0x63a
created by github.com/minio/minio-go.Client.GetObject
	/Users/aaronwalker/go/src/github.com/minio/minio-go/api-get-object.go:99 +0x460

goroutine 290 [select, 8 minutes]:
github.com/minio/minio-go.Client.GetObject.func1(0xc8202a22a0, 0xc8202a2300, 0xc8202a2360, 0xc8201caec0, 0xc8201caed0, 0xc820436140, 0xc8203b42d0, 0x23, 0xc8203b4300, 0x23)
	/Users/aaronwalker/go/src/github.com/minio/minio-go/api-get-object.go:59 +0x63a
created by github.com/minio/minio-go.Client.GetObject
	/Users/aaronwalker/go/src/github.com/minio/minio-go/api-get-object.go:99 +0x460

goroutine 202 [select, 9 minutes]:
github.com/minio/minio-go.Client.GetObject.func1(0xc8203c1680, 0xc8203c16e0, 0xc8203c1740, 0xc820190f40, 0xc820190f50, 0xc8204f6320, 0xc8201b8360, 0x1e, 0xc8201b8800, 0x1e)
	/Users/aaronwalker/go/src/github.com/minio/minio-go/api-get-object.go:59 +0x63a
created by github.com/minio/minio-go.Client.GetObject
	/Users/aaronwalker/go/src/github.com/minio/minio-go/api-get-object.go:99 +0x460

goroutine 372 [select, 8 minutes]:
github.com/minio/minio-go.Client.GetObject.func1(0xc8203c0180, 0xc8203c01e0, 0xc8203c0240, 0xc8201dc990, 0xc8201dc9a0, 0xc8200b5f40, 0xc82019e3a0, 0x1e, 0xc820329230, 0x2e)
	/Users/aaronwalker/go/src/github.com/minio/minio-go/api-get-object.go:59 +0x63a
created by github.com/minio/minio-go.Client.GetObject
	/Users/aaronwalker/go/src/github.com/minio/minio-go/api-get-object.go:99 +0x460

goroutine 240 [select, 8 minutes]:
net/http.(*persistConn).readLoop(0xc82034a0d0)
	/usr/local/Cellar/go/1.6/libexec/src/net/http/transport.go:1178 +0x118c
created by net/http.(*Transport).dialConn
	/usr/local/Cellar/go/1.6/libexec/src/net/http/transport.go:853 +0x16f0

goroutine 263 [select, 8 minutes]:
github.com/minio/minio-go.Client.GetObject.func1(0xc820416420, 0xc820416480, 0xc8204164e0, 0xc8201bdc30, 0xc8201bdc50, 0xc8202e1cc0, 0xc8201cc220, 0x1e, 0xc8203357a0, 0x1e)
	/Users/aaronwalker/go/src/github.com/minio/minio-go/api-get-object.go:59 +0x63a
created by github.com/minio/minio-go.Client.GetObject
	/Users/aaronwalker/go/src/github.com/minio/minio-go/api-get-object.go:99 +0x460

goroutine 629 [IO wait]:
net.runtime_pollWait(0x2300d00, 0x72, 0x13fc9)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/netpoll.go:160 +0x63
net.(*pollDesc).Wait(0xc8205e31e0, 0x72, 0x0, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/net/fd_poll_runtime.go:73 +0x56
net.(*pollDesc).WaitRead(0xc8205e31e0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/net/fd_poll_runtime.go:78 +0x44
net.(*netFD).Read(0xc8205e3180, 0xc821393000, 0x1000, 0x1000, 0x0, 0x2080050, 0xc820010058)
	/usr/local/Cellar/go/1.6/libexec/src/net/fd_unix.go:250 +0x27b
net.(*conn).Read(0xc8200281a0, 0xc821393000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/net/net.go:172 +0x121
net.(*TCPConn).Read(0xc8200281a0, 0xc821393000, 0x1000, 0x1000, 0xc820310fe0, 0x0, 0x0)
	<autogenerated>:68 +0x7d
crypto/tls.(*block).readFromUntil(0xc82049b260, 0x2301138, 0xc8200281a0, 0x5, 0x0, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/crypto/tls/conn.go:460 +0x143
crypto/tls.(*Conn).readRecord(0xc820386c00, 0x762d17, 0x0, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/crypto/tls/conn.go:562 +0x3aa
crypto/tls.(*Conn).Read(0xc820386c00, 0xc82051c000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/crypto/tls/conn.go:939 +0x1bd
net/http.noteEOFReader.Read(0x2340a98, 0xc820386c00, 0xc82034ae38, 0xc82051c000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/net/http/transport.go:1683 +0x75
net/http.(*noteEOFReader).Read(0xc820311080, 0xc82051c000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	<autogenerated>:284 +0xf8
bufio.(*Reader).fill(0xc820280240)
	/usr/local/Cellar/go/1.6/libexec/src/bufio/bufio.go:97 +0x365
bufio.(*Reader).ReadSlice(0xc820280240, 0x66ac0a, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/bufio/bufio.go:328 +0x5a9
bufio.(*Reader).ReadLine(0xc820280240, 0x0, 0x0, 0x0, 0xa00c8214adb00, 0x0, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/bufio/bufio.go:357 +0x6d
net/textproto.(*Reader).readLineSlice(0xc8214adc40, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/net/textproto/reader.go:55 +0xa3
net/textproto.(*Reader).ReadLine(0xc8214adc40, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/net/textproto/reader.go:36 +0x4e
net/http.ReadResponse(0xc820280240, 0xc8203ebc00, 0xc8214adc98, 0x0, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/net/http/response.go:138 +0x183
net/http.(*persistConn).readResponse(0xc82034add0, 0xc8203ebc00, 0xc820416180, 0x1, 0xc820416060, 0xc8204160c0, 0xc820141680, 0x0, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/net/http/transport.go:1240 +0x139
net/http.(*persistConn).readLoop(0xc82034add0)
	/usr/local/Cellar/go/1.6/libexec/src/net/http/transport.go:1086 +0x4ae
created by net/http.(*Transport).dialConn
	/usr/local/Cellar/go/1.6/libexec/src/net/http/transport.go:853 +0x16f0

goroutine 241 [select, 8 minutes]:
net/http.(*persistConn).writeLoop(0xc82034a0d0)
	/usr/local/Cellar/go/1.6/libexec/src/net/http/transport.go:1273 +0x563
created by net/http.(*Transport).dialConn
	/usr/local/Cellar/go/1.6/libexec/src/net/http/transport.go:854 +0x1715

goroutine 280 [select, 8 minutes]:
net/http.(*persistConn).writeLoop(0xc82006c340)
	/usr/local/Cellar/go/1.6/libexec/src/net/http/transport.go:1273 +0x563
created by net/http.(*Transport).dialConn
	/usr/local/Cellar/go/1.6/libexec/src/net/http/transport.go:854 +0x1715

goroutine 630 [IO wait]:
net.runtime_pollWait(0x2300d00, 0x77, 0x13fc9)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/netpoll.go:160 +0x63
net.(*pollDesc).Wait(0xc8205e31e0, 0x77, 0x0, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/net/fd_poll_runtime.go:73 +0x56
net.(*pollDesc).WaitWrite(0xc8205e31e0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/net/fd_poll_runtime.go:82 +0x44
net.(*netFD).Write(0xc8205e3180, 0xc820544000, 0x1035, 0x2000, 0x0, 0x2080050, 0xc820010058)
	/usr/local/Cellar/go/1.6/libexec/src/net/fd_unix.go:336 +0x494
net.(*conn).Write(0xc8200281a0, 0xc820544000, 0x1035, 0x2000, 0x14, 0x0, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/net/net.go:184 +0x121
net.(*TCPConn).Write(0xc8200281a0, 0xc820544000, 0x1035, 0x2000, 0x1000, 0x0, 0x0)
	<autogenerated>:69 +0x7d
crypto/tls.(*Conn).writeRecord(0xc820386c00, 0x762d17, 0xc82051d000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/crypto/tls/conn.go:769 +0x81f
crypto/tls.(*Conn).Write(0xc820386c00, 0xc82051d000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/crypto/tls/conn.go:915 +0x5cb
bufio.(*Writer).flush(0xc8201f3340, 0x0, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/bufio/bufio.go:562 +0x1a8
bufio.(*Writer).ReadFrom(0xc8201f3340, 0x2084ab8, 0xc820496240, 0x16ba000, 0x0, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/bufio/bufio.go:686 +0x1e0
io.copyBuffer(0x208f670, 0xc8201f3340, 0x2084ab8, 0xc820496240, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/io/io.go:374 +0x1a6
io.Copy(0x208f670, 0xc8201f3340, 0x2084ab8, 0xc820496240, 0xc8201d6e00, 0x0, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/io/io.go:350 +0x79
net/http.(*transferWriter).WriteBody(0xc82014a850, 0x208f670, 0xc8201f3340, 0x0, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/net/http/transfer.go:225 +0xbbf
net/http.(*Request).write(0xc8203ebc00, 0x208f670, 0xc8201f3340, 0x0, 0xc821391b00, 0xc820476f80, 0x0, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/net/http/request.go:497 +0xe6d
net/http.(*persistConn).writeLoop(0xc82034add0)
	/usr/local/Cellar/go/1.6/libexec/src/net/http/transport.go:1279 +0x383
created by net/http.(*Transport).dialConn
	/usr/local/Cellar/go/1.6/libexec/src/net/http/transport.go:854 +0x1715

goroutine 593 [select]:
github.com/minio/minio-go.Client.newRetryTimer.func2(0xc821385380, 0x5, 0xc821385320, 0xc821391140)
	/Users/aaronwalker/go/src/github.com/minio/minio-go/retry.go:66 +0x189
created by github.com/minio/minio-go.Client.newRetryTimer
	/Users/aaronwalker/go/src/github.com/minio/minio-go/retry.go:75 +0x1c5

goroutine 603 [select]:
net/http.(*persistConn).roundTrip(0xc82034add0, 0xc8202d9eb0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/net/http/transport.go:1469 +0x1442
net/http.(*Transport).RoundTrip(0xc8200f4000, 0xc8203ebc00, 0xc8200f4000, 0x0, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/net/http/transport.go:320 +0xcc3
net/http.send(0xc8203ebc00, 0x20847f8, 0xc8200f4000, 0x0, 0x0, 0x0, 0xf7, 0x0, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/net/http/client.go:260 +0x962
net/http.(*Client).send(0xc8201eb2c0, 0xc8203ebc00, 0x0, 0x0, 0x0, 0xd, 0x0, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/net/http/client.go:155 +0x220
net/http.(*Client).doFollowingRedirects(0xc8201eb2c0, 0xc8203ebc00, 0x7627b0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/net/http/client.go:475 +0xb35
net/http.(*Client).Do(0xc8201eb2c0, 0xc8203ebc00, 0x3dc2a, 0x0, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/net/http/client.go:191 +0x21b
github.com/minio/minio-go.Client.do(0xc82000a0ab, 0x14, 0xc8200120cb, 0x28, 0x1, 0x0, 0x6b3510, 0x17, 0x6698c0, 0x5, ...)
	/Users/aaronwalker/go/src/github.com/minio/minio-go/api.go:368 +0x63
github.com/minio/minio-go.Client.executeMethod(0xc82000a0ab, 0x14, 0xc8200120cb, 0x28, 0x1, 0x0, 0x6b3510, 0x17, 0x6698c0, 0x5, ...)
	/Users/aaronwalker/go/src/github.com/minio/minio-go/api.go:451 +0x427
github.com/minio/minio-go.Client.uploadPart(0xc82000a0ab, 0x14, 0xc8200120cb, 0x28, 0x1, 0x0, 0x6b3510, 0x17, 0x6698c0, 0x5, ...)
	/Users/aaronwalker/go/src/github.com/minio/minio-go/api-put-object-multipart.go:304 +0xaec
github.com/minio/minio-go.Client.putObjectMultipartFromFile(0xc82000a0ab, 0x14, 0xc8200120cb, 0x28, 0x1, 0x0, 0x6b3510, 0x17, 0x6698c0, 0x5, ...)
	/Users/aaronwalker/go/src/github.com/minio/minio-go/api-put-object-file.go:211 +0xeed
github.com/minio/minio-go.Client.FPutObject(0xc82000a0ab, 0x14, 0xc8200120cb, 0x28, 0x1, 0x0, 0x6b3510, 0x17, 0x6698c0, 0x5, ...)
	/Users/aaronwalker/go/src/github.com/minio/minio-go/api-put-object-file.go:108 +0xdea
github.com/minio/minio-go.TestResumableFPutObject(0xc8203561b0)
	/Users/aaronwalker/go/src/github.com/minio/minio-go/api_functional_v4_test.go:631 +0x131c
testing.tRunner(0xc8203561b0, 0x90fae0)
	/usr/local/Cellar/go/1.6/libexec/src/testing/testing.go:473 +0xdd
created by testing.RunTests
	/usr/local/Cellar/go/1.6/libexec/src/testing/testing.go:582 +0xae3

goroutine 496 [select, 3 minutes]:
github.com/minio/minio-go.Client.GetObject.func1(0xc821385e60, 0xc821385ec0, 0xc821385f20, 0xc82146cba0, 0xc82146cbb0, 0xc821349ae0, 0xc820394f20, 0x1e, 0xc820467b30, 0x28)
	/Users/aaronwalker/go/src/github.com/minio/minio-go/api-get-object.go:59 +0x63a
created by github.com/minio/minio-go.Client.GetObject
	/Users/aaronwalker/go/src/github.com/minio/minio-go/api-get-object.go:99 +0x460

rax    0xe
rbx    0x911fe0
rcx    0x7fff5fbff470
rdx    0x7fff5fbff4e8
rdi    0x1003
rsi    0x1c9e
rbp    0x1003
rsp    0x7fff5fbff470
r8     0x911fe0
r9     0x50
r10    0x3ae5f7c2771
r11    0x286
r12    0x10d2b3be29c91
r13    0x11e91f13dc0f0
r14    0x1464f5b40798d800
r15    0xc8202851a0
rip    0x63a5b
rflags 0x286
cs     0x7
fs     0x0
gs     0x0
*** Test killed with quit: ran too long (10m0s).
FAIL	github.com/minio/minio-go	600.325s
```

**Comment by harshavardhana** [comment]
The actual error is in 'retry' code

```
github.com/minio/minio-go.Client.executeMethod(0xc82001410b, 0x14, 0xc8200121cb, 0x28, 0x1, 0x0, 0xab26d0, 0x17, 0xa688e8, 0x5, ...)
	/home/harsha/mygo/src/github.com/minio/minio-go/api.go:451 +0x427
github.com/minio/minio-go.Client.uploadPart(0xc82001410b, 0x14, 0xc8200121cb, 0x28, 0x1, 0x0, 0xab26d0, 0x17, 0xa688e8, 0x5, ...)
	/home/harsha/mygo/src/github.com/minio/minio-go/api-put-object-multipart.go:304 +0xaec
github.com/minio/minio-go.Client.putObjectMultipartFromFile(0xc82001410b, 0x14, 0xc8200121cb, 0x28, 0x1, 0x0, 0xab26d0, 0x17, 0xa688e8, 0x5, ...)
	/home/harsha/mygo/src/github.com/minio/minio-go/api-put-object-file.go:211 +0xeed
github.com/minio/minio-go.Client.FPutObject(0xc82001410b, 0x14, 0xc8200121cb, 0x28, 0x1, 0x0, 0xab26d0, 0x17, 0xa688e8, 0x5, ...)
	/home/harsha/mygo/src/github.com/minio/minio-go/api-put-object-file.go:108 +0xdea
github.com/minio/minio-go.TestResumableFPutObject(0xc8200b25a0)
	/home/harsha/mygo/src/github.com/minio/minio-go/api_functional_v4_test.go:631 +0x131c
testing.tRunner(0xc8200b25a0, 0xd0f620)
	/home/harsha/.gimme/versions/go1.6.linux.amd64/src/testing/testing.go:473 +0xdd
created by testing.RunTests
	/home/harsha/.gimme/versions/go1.6.linux.amd64/src/testing/testing.go:582 +0xae3
```

**Comment by harshavardhana** [comment]
Not reproducible anymore, closing.
